### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by sergiyuvarov** [anetrusov/ZabbixDBA#44]
Hello,

I can't import template Template_Oracle.xml. I receive a such error:

Invalid tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)/item_prototypes/item_prototype(1)": unexpected tag "application_prototypes".

**Comment by netrusov** [comment]
@sergiyuvarov 

Hello,

Which version of Zabbix do you use?
I'm afraid that it might be incompatible with newer versions (didn't check for long time).

Thanks.

**Comment by sergiyuvarov** [comment]
Hello,

we are using 3.2.3

**Comment by netrusov** [comment]
@sergiyuvarov 

Can you please remove those 2 lines (line numbers: 2296, 2340) and try again? If it works, I'll add this fix to the next release.

Thanks.

**Comment by sergiyuvarov** [comment]
To import template I removed all lines: application_prototypes and dependencies.

When I configured zabbix agent I set the hostname in zabbix_agentd.conf. This hostname points
to the host in the zabbix server configuration. I can't find the same parameter in your plugin.
How can information from this plugin be connected to the host in zabbix server?

**Comment by netrusov** [comment]
@sergiyuvarov 

Thanks, I'll test template compatibility across different versions of Zabbix and include fix into the next release.

I'm sure that the issue is with names. They must be the same at Zabbix server and zdba.
Please refer to [this](https://github.com/anetrusov/ZabbixDBA/issues/43#issuecomment-272820979) comment and [this](https://github.com/anetrusov/ZabbixDBA/blob/master/docs/Configuration.md#db) section at configuration docs.

**Comment by sergiyuvarov** [comment]
Thanks. It is working now.
